# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188Y94AoVsRa_Jsu3iQ9pObJTvziW3_ES
"""

import numpy as np
x=2
y=3
z=x+y
print(z)

import matplotlib #visaulization 3D, 2D...
import matplotlib.pyplot as plt #for graph
x=np.linspace(0,1,100)#array of numbers
y=np.sin(x)
print(x)
print("\n")
print(y)
plt.plot(x,y,'.r') #array of x and f(x) that f(x) is y , .r is color red
plt.show() #to see the graph